using ChromaDB.Client.Common;
using NUnit.Framework;

namespace ChromaDB.Client.Tests;

// The stems are those of the Python package snowballstemmer 3.1.1: snowballstemmer.stemmer("english").stemWord(word).
[TestFixture]
public class SnowballEnglishStemmerTests
{
	static readonly SnowballEnglishStemmer Stemmer = new();

	// Exceptional forms, and words near them.
	[TestCase("andes", "andes")]
	[TestCase("atlas", "atlas")]
	[TestCase("bias", "bias")]
	[TestCase("cosmos", "cosmos")]
	[TestCase("early", "earli")]
	[TestCase("gently", "gentl")]
	[TestCase("howe", "howe")]
	[TestCase("idly", "idl")]
	[TestCase("news", "news")]
	[TestCase("only", "onli")]
	[TestCase("singly", "singl")]
	[TestCase("skies", "sky")]
	[TestCase("skis", "ski")]
	[TestCase("sky", "sky")]
	[TestCase("ugly", "ugli")]
	[TestCase("atlases", "atlas")]
	[TestCase("biases", "bias")]
	[TestCase("earlier", "earlier")]
	[TestCase("gentle", "gentl")]
	[TestCase("howes", "how")]
	[TestCase("idle", "idl")]
	[TestCase("newsy", "newsi")]
	[TestCase("skier", "skier")]
	[TestCase("skiing", "ski")]
	[TestCase("skied", "ski")]
	[TestCase("ugliness", "ugli")]
	// Prefixes that set R1 (arsen, commun, emerg, gener, inter, later, organ, past, univers).
	[TestCase("arsenal", "arsenal")]
	[TestCase("arsenic", "arsenic")]
	[TestCase("communism", "communism")]
	[TestCase("community", "communiti")]
	[TestCase("communication", "communic")]
	[TestCase("emergency", "emergenc")]
	[TestCase("emerging", "emerg")]
	[TestCase("general", "general")]
	[TestCase("generally", "general")]
	[TestCase("generate", "generat")]
	[TestCase("generation", "generat")]
	[TestCase("generous", "generous")]
	[TestCase("interest", "interest")]
	[TestCase("international", "internat")]
	[TestCase("later", "later")]
	[TestCase("laterally", "lateral")]
	[TestCase("organ", "organ")]
	[TestCase("organization", "organiz")]
	[TestCase("organs", "organ")]
	[TestCase("past", "past")]
	[TestCase("pastry", "pastri")]
	[TestCase("universal", "universal")]
	[TestCase("universe", "univers")]
	[TestCase("university", "universiti")]
	// Words shorter than 3 characters stay as they are; 3 is enough.
	[TestCase("a", "a")]
	[TestCase("i", "i")]
	[TestCase("ab", "ab")]
	[TestCase("by", "by")]
	[TestCase("is", "is")]
	[TestCase("my", "my")]
	[TestCase("us", "us")]
	[TestCase("''", "''")]
	[TestCase("'a", "'a")]
	[TestCase("y", "y")]
	[TestCase("Y", "Y")]
	[TestCase("abs", "ab")]
	[TestCase("bus", "bus")]
	[TestCase("gas", "gas")]
	[TestCase("yes", "yes")]
	[TestCase("dye", "dye")]
	[TestCase("eye", "eye")]
	[TestCase("spy", "spi")]
	[TestCase("ski", "ski")]
	[TestCase("its", "it")]
	[TestCase("cry", "cri")]
	[TestCase("fly", "fli")]
	[TestCase("aye", "aye")]
	[TestCase("ies", "ie")]
	// Apostrophes: one at the start, and ', 's or 's' at the end.
	[TestCase("'tis", "tis")]
	[TestCase("boy's", "boy")]
	[TestCase("boys'", "boy")]
	[TestCase("boys's", "boy")]
	[TestCase("dog's'", "dog")]
	[TestCase("o'clock", "o'clock")]
	[TestCase("don't", "don't")]
	[TestCase("rock'n'roll", "rock'n'rol")]
	[TestCase("''yes", "'ye")]
	[TestCase("''''", "''")]
	[TestCase("'y", "'y")]
	[TestCase("it's", "it")]
	[TestCase("cats''", "cats'")]
	[TestCase("james'", "jame")]
	[TestCase("james's", "jame")]
	[TestCase("'ss", "ss")]
	[TestCase("'cats'", "cat")]
	[TestCase("''s", "")]
	// y at the start or after a vowel is a consonant.
	[TestCase("yellow", "yellow")]
	[TestCase("youth", "youth")]
	[TestCase("yay", "yay")]
	[TestCase("yoyo", "yoyo")]
	[TestCase("kayak", "kayak")]
	[TestCase("kayaking", "kayak")]
	[TestCase("say", "say")]
	[TestCase("says", "say")]
	[TestCase("saying", "say")]
	[TestCase("boy", "boy")]
	[TestCase("boyish", "boyish")]
	[TestCase("toying", "toy")]
	[TestCase("employ", "employ")]
	[TestCase("employment", "employ")]
	[TestCase("playing", "play")]
	[TestCase("buyer", "buyer")]
	[TestCase("obeying", "obey")]
	[TestCase("conveyance", "convey")]
	[TestCase("annoyance", "annoy")]
	[TestCase("rhythm", "rhythm")]
	[TestCase("yyy", "yyy")]
	[TestCase("eyeing", "eye")]
	[TestCase("ayy", "ayi")]
	// Step 1a.
	[TestCase("caresses", "caress")]
	[TestCase("ponies", "poni")]
	[TestCase("ties", "tie")]
	[TestCase("cries", "cri")]
	[TestCase("tied", "tie")]
	[TestCase("cried", "cri")]
	[TestCase("spied", "spi")]
	[TestCase("died", "die")]
	[TestCase("caress", "caress")]
	[TestCase("kisses", "kiss")]
	[TestCase("buses", "buse")]
	[TestCase("census", "census")]
	[TestCase("gaps", "gap")]
	[TestCase("kiwis", "kiwi")]
	[TestCase("cats", "cat")]
	[TestCase("this", "this")]
	[TestCase("abyss", "abyss")]
	[TestCase("viruses", "virus")]
	[TestCase("status", "status")]
	[TestCase("chaos", "chao")]
	[TestCase("species", "speci")]
	[TestCase("s's", "s")]
	[TestCase("'by'", "by")]
	// Step 1b: eed, ed, ing, edly, ingly.
	[TestCase("feed", "feed")]
	[TestCase("agreed", "agre")]
	[TestCase("freed", "freed")]
	[TestCase("proceed", "proceed")]
	[TestCase("proceeding", "proceed")]
	[TestCase("exceeded", "exceed")]
	[TestCase("succeed", "succeed")]
	[TestCase("plastered", "plaster")]
	[TestCase("bled", "bled")]
	[TestCase("motoring", "motor")]
	[TestCase("sing", "sing")]
	[TestCase("hoped", "hope")]
	[TestCase("hoping", "hope")]
	[TestCase("hopping", "hop")]
	[TestCase("conflated", "conflat")]
	[TestCase("troubled", "troubl")]
	[TestCase("sized", "size")]
	[TestCase("tanned", "tan")]
	[TestCase("hissing", "hiss")]
	[TestCase("fizzed", "fizz")]
	[TestCase("failing", "fail")]
	[TestCase("filing", "file")]
	[TestCase("added", "add")]
	[TestCase("ebbed", "ebb")]
	[TestCase("egged", "egg")]
	[TestCase("offed", "off")]
	[TestCase("planned", "plan")]
	[TestCase("stopping", "stop")]
	[TestCase("stuffed", "stuf")]
	[TestCase("rated", "rate")]
	[TestCase("tabled", "tabl")]
	[TestCase("liking", "like")]
	[TestCase("luxuriated", "luxuri")]
	[TestCase("opened", "open")]
	[TestCase("aped", "ape")]
	[TestCase("pasted", "paste")]
	[TestCase("pasting", "paste")]
	[TestCase("reproceed", "reproce")]
	[TestCase("byed", "by")]
	// Step 1b: ing after y, even, cann, inn, earr, herr and out.
	[TestCase("dying", "die")]
	[TestCase("lying", "lie")]
	[TestCase("tying", "tie")]
	[TestCase("vying", "vie")]
	[TestCase("eying", "eye")]
	[TestCase("inning", "inning")]
	[TestCase("innings", "inning")]
	[TestCase("outing", "outing")]
	[TestCase("outings", "outing")]
	[TestCase("canning", "canning")]
	[TestCase("evening", "evening")]
	[TestCase("evenings", "evening")]
	[TestCase("earring", "earring")]
	[TestCase("herring", "herring")]
	[TestCase("herrings", "herring")]
	[TestCase("sprouting", "sprout")]
	[TestCase("spying", "spi")]
	[TestCase("flying", "fli")]
	[TestCase("buying", "buy")]
	// Step 1b: edly and ingly.
	[TestCase("markedly", "mark")]
	[TestCase("excitedly", "excit")]
	[TestCase("knowingly", "know")]
	[TestCase("seemingly", "seem")]
	[TestCase("hurriedly", "hurri")]
	[TestCase("exceedingly", "exceed")]
	[TestCase("supposedly", "suppos")]
	[TestCase("amazingly", "amaz")]
	[TestCase("agreedly", "agre")]
	// Step 1c.
	[TestCase("happy", "happi")]
	[TestCase("ploy", "ploy")]
	[TestCase("fry", "fri")]
	[TestCase("sly", "sli")]
	[TestCase("apology", "apolog")]
	[TestCase("enjoy", "enjoy")]
	[TestCase("flatly", "flat")]
	[TestCase("obey", "obey")]
	[TestCase("by's", "by")]
	// Step 2.
	[TestCase("hesitancy", "hesit")]
	[TestCase("valency", "valenc")]
	[TestCase("geology", "geolog")]
	[TestCase("pedagogy", "pedagogi")]
	[TestCase("analogy", "analog")]
	[TestCase("quickly", "quick")]
	[TestCase("warmly", "warm")]
	[TestCase("deeply", "deepli")]
	[TestCase("nicely", "nice")]
	[TestCase("badly", "bad")]
	[TestCase("mostly", "most")]
	[TestCase("highly", "high")]
	[TestCase("openly", "open")]
	[TestCase("fairly", "fair")]
	[TestCase("slowly", "slowli")]
	[TestCase("conformably", "conform")]
	[TestCase("radically", "radic")]
	[TestCase("carefully", "care")]
	[TestCase("beautifully", "beauti")]
	[TestCase("carelessly", "careless")]
	[TestCase("analogously", "analog")]
	[TestCase("differently", "differ")]
	[TestCase("formality", "formal")]
	[TestCase("sensibility", "sensibl")]
	[TestCase("sensitivity", "sensit")]
	[TestCase("conditional", "condit")]
	[TestCase("relational", "relat")]
	[TestCase("feudalism", "feudal")]
	[TestCase("predication", "predic")]
	[TestCase("vietnamization", "vietnam")]
	[TestCase("digitizer", "digit")]
	[TestCase("operator", "oper")]
	[TestCase("decisiveness", "decis")]
	[TestCase("hopefulness", "hope")]
	[TestCase("callousness", "callous")]
	[TestCase("geologist", "geolog")]
	[TestCase("biologist", "biolog")]
	[TestCase("rely", "reli")]
	// Step 3.
	[TestCase("triplicate", "triplic")]
	[TestCase("formative", "format")]
	[TestCase("native", "nativ")]
	[TestCase("formalize", "formal")]
	[TestCase("electricity", "electr")]
	[TestCase("electrical", "electr")]
	[TestCase("additional", "addit")]
	[TestCase("sensational", "sensat")]
	[TestCase("hopeful", "hope")]
	[TestCase("goodness", "good")]
	[TestCase("demonstrative", "demonstr")]
	[TestCase("argumentative", "argument")]
	[TestCase("conditionally", "condit")]
	[TestCase("sensationally", "sensat")]
	// Step 4.
	[TestCase("gyroscopic", "gyroscop")]
	[TestCase("allowance", "allow")]
	[TestCase("inference", "infer")]
	[TestCase("adjustable", "adjust")]
	[TestCase("defensible", "defens")]
	[TestCase("activate", "activ")]
	[TestCase("effective", "effect")]
	[TestCase("bowdlerize", "bowdler")]
	[TestCase("angularity", "angular")]
	[TestCase("revival", "reviv")]
	[TestCase("nationalism", "nation")]
	[TestCase("adoption", "adopt")]
	[TestCase("erosion", "eros")]
	[TestCase("onion", "onion")]
	[TestCase("airliner", "airlin")]
	[TestCase("homologous", "homolog")]
	[TestCase("irritant", "irrit")]
	[TestCase("dependent", "depend")]
	[TestCase("adjustment", "adjust")]
	[TestCase("replacement", "replac")]
	[TestCase("opinion", "opinion")]
	[TestCase("champion", "champion")]
	// Step 5.
	[TestCase("probate", "probat")]
	[TestCase("rate", "rate")]
	[TestCase("cease", "ceas")]
	[TestCase("controlling", "control")]
	[TestCase("roll", "roll")]
	[TestCase("fall", "fall")]
	[TestCase("skill", "skill")]
	[TestCase("parallel", "parallel")]
	// Other words.
	[TestCase("consign", "consign")]
	[TestCase("consigned", "consign")]
	[TestCase("consigning", "consign")]
	[TestCase("consignment", "consign")]
	[TestCase("consist", "consist")]
	[TestCase("consistency", "consist")]
	[TestCase("knightly", "knight")]
	[TestCase("knives", "knive")]
	// Digits.
	[TestCase("1990s", "1990s")]
	[TestCase("3rd", "3rd")]
	[TestCase("x86", "x86")]
	[TestCase("abc123", "abc123")]
	[TestCase("1st", "1st")]
	[TestCase("h2o", "h2o")]
	[TestCase("mp3s", "mp3s")]
	[TestCase("covid19", "covid19")]
	[TestCase("24hours", "24hour")]
	// Uppercase letters are not vowels, as in Python.
	[TestCase("Running", "Run")]
	[TestCase("RUNNING", "RUNNING")]
	[TestCase("Cats", "Cat")]
	[TestCase("CATS", "CATS")]
	[TestCase("Yellow", "Yellow")]
	[TestCase("YES", "YES")]
	[TestCase("Happy", "Happi")]
	// Letters outside ASCII are not vowels, as in Python.
	[TestCase("caf\u00E9", "caf\u00E9")]
	[TestCase("caf\u00E9s", "caf\u00E9")]
	[TestCase("na\u00EFve", "na\u00EFv")]
	[TestCase("na\u00EFvely", "na\u00EFv")]
	[TestCase("r\u00E9sum\u00E9s", "r\u00E9sum\u00E9")]
	[TestCase("\u00FCber", "\u00FCber")]
	[TestCase("jalape\u00F1os", "jalape\u00F1o")]
	[TestCase("fa\u00E7ades", "fa\u00E7ad")]
	[TestCase("fianc\u00E9es", "fianc\u00E9")]
	[TestCase("\u0395\u03BB\u03BB\u03B7\u03BD\u03B9\u03BA\u03AC", "\u0395\u03BB\u03BB\u03B7\u03BD\u03B9\u03BA\u03AC")]
	[TestCase("\u03BB\u03CC\u03B3\u03BF\u03B9", "\u03BB\u03CC\u03B3\u03BF\u03B9")]
	[TestCase("\u65E5\u672C\u8A9E", "\u65E5\u672C\u8A9E")]
	[TestCase("\u0440\u0443\u0441\u0441\u043A\u0438\u0439", "\u0440\u0443\u0441\u0441\u043A\u0438\u0439")]
	// A character outside the BMP is one character, as in Python.
	[TestCase("\U0001F600ies", "\U0001F600ie")]
	[TestCase("a\U0001F600ed", "a\U0001F600e")]
	[TestCase("rocket\U0001F680s", "rocket\U0001F680")]
	[TestCase("\U0001F600", "\U0001F600")]
	[TestCase("\U0001F600\U0001F600", "\U0001F600\U0001F600")]
	[TestCase("\U0001F600s", "\U0001F600s")]
	[TestCase("\U0001F600\U0001F600s", "\U0001F600\U0001F600s")]
	[TestCase("\U0001D44Eing", "\U0001D44Eing")]
	public void Stem(string word, string stem)
	{
		Assert.That(Stemmer.Stem(word), Is.EqualTo(stem));
	}

	// One instance stems from several threads at once.
	[Test]
	public void SameStemsFromSeveralThreads()
	{
		var words = Enumerable.Repeat(new[] { "generously", "caresses", "dying", "skies", "\U0001F600ies", "hopping", "conditionally", "yellow" }, 1000)
			.SelectMany(x => x)
			.ToArray();
		var expected = words.Select(Stemmer.Stem).ToArray();
		var stems = new string[words.Length];
		Parallel.For(0, words.Length, i => stems[i] = Stemmer.Stem(words[i]));
		Assert.That(stems, Is.EqualTo(expected));
	}
}
