"""Generates ChromaDB.Client/Common/Bm25Unicode.cs: the Unicode rules of Python that the BM25 tokenizer of Chroma follows.

Run it with the Python that the BM25 function of Chroma runs on; it writes the tables of its Unicode version, so that ChromaBm25 gives
the same tokens on every .NET runtime, whatever Unicode version the runtime knows:
    python tools/generate_bm25_unicode.py > ChromaDB.Client/Common/Bm25Unicode.cs
"""
import sys
import unicodedata

MAX = 0x110000


def ranges(predicate):
    result, start = [], None
    for c in range(MAX + 1):
        inside = c < MAX and not (0xD800 <= c <= 0xDFFF) and predicate(c)
        if inside and start is None:
            start = c
        elif not inside and start is not None:
            result.append((start, c - 1))
            start = None
    return result


def word(c):  # \w of re in Unicode: str.isalnum() or "_"
    return chr(c).isalnum() or c == 0x5F


def space(c):  # \s of re in Unicode, and str.isspace()
    return chr(c).isspace()


# The Final_Sigma context of str.lower(), read from the behavior of Python itself, for every character: the text has only word
# characters and spaces, but the stopwords are lowercased as they are. "X" + sigma ends with a final sigma when X is cased and not
# case-ignorable; "A" + X + sigma ends with one when X is case-ignorable or cased.
def final(text):
    return text.lower().endswith("ς")


def cased(c):
    return final(chr(c) + "Σ")


def case_ignorable(c):
    return not final(chr(c) + "Σ") and final("A" + chr(c) + "Σ")


def array(name, items):
    lines = []
    for i in range(0, len(items), 16):
        lines.append("\t\t" + ", ".join(f"0x{x:X}" for x in items[i:i + 16]) + ",")
    return f"\tinternal static readonly int[] {name} =\n\t[\n" + "\n".join(lines) + "\n\t];\n"


def flat(rs):
    return [x for r in rs for x in r]


def escape(text):
    return "".join(f"\\u{ord(x):04X}" if ord(x) < 0x10000 else f"\\U{ord(x):08X}" for x in text)


lower = [(c, chr(c).lower()) for c in range(MAX) if not (0xD800 <= c <= 0xDFFF) and chr(c).lower() != chr(c)]
single = [(c, ord(l)) for c, l in lower if len(l) == 1]
multi = [(c, l) for c, l in lower if len(l) != 1]

out = sys.stdout
out.write("// <auto-generated>\n")
out.write(f"// Generated by tools/generate_bm25_unicode.py with Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.\n")
out.write("// </auto-generated>\n\n")
out.write("namespace ChromaDB.Client.Common;\n\n")
out.write("// The Unicode rules of Python that the BM25 tokenizer follows. The ranges are pairs of first and last code point, in order.\n")
out.write("internal static class Bm25Unicode\n{\n")
out.write("\t// \\w: str.isalnum() or \"_\".\n")
out.write(array("WordRanges", flat(ranges(word))))
out.write("\n\t// \\s: str.isspace().\n")
out.write(array("SpaceRanges", flat(ranges(space))))
out.write("\n\t// The characters that are cased and not case-ignorable, for the final sigma.\n")
out.write(array("CasedRanges", flat(ranges(cased))))
out.write("\n\t// The characters that are case-ignorable, for the final sigma.\n")
out.write(array("CaseIgnorableRanges", flat(ranges(case_ignorable))))
out.write("\n\t// str.lower() of the characters that change, without the context of the final sigma: pairs of code point and lowercase.\n")
out.write(array("Lowercase", flat(single)))
out.write("\n\t// The ones whose lowercase has more than one code point.\n")
out.write("\tinternal static readonly Dictionary<int, string> LowercaseLonger = new()\n\t{\n")
for c, l in multi:
    out.write(f"\t\t[0x{c:X}] = \"{escape(l)}\",\n")
out.write("\t};\n}\n")
